name = "freight-bill-tracker"
main = "src/index.ts"
compatibility_date = "2025-03-31"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "freight-bills-db"
database_id = "freight-bills-db-local"

[[r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "freight-bill-documents-local"

[vars]
TEAM_DOMAIN = "https://dayserver.cloudflareaccess.com"
JWT_VALIDATION_DISABLED = "true"

[env.production]

name = "freight-bill-tracker"

[env.production.vars]
TEAM_DOMAIN = "https://dayserver.cloudflareaccess.com"
JWT_VALIDATION_DISABLED = "false"

[env.production.secrets]
required = ["POLICY_AUD"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "freight-bills-db"
database_id = "a0f777a6-ff9f-467f-a306-6474a6845597"

[[env.production.r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "freight-bill-documents-prod"

[env.staging]

name = "freight-bill-tracker-staging"
workers_dev = true
preview_urls = true

[env.staging.vars]
TEAM_DOMAIN = "https://dayserver.cloudflareaccess.com"
JWT_VALIDATION_DISABLED = "false"

[env.staging.secrets]
required = ["POLICY_AUD"]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "freight-bills-staging"
database_id = "b8860df5-0f0f-4643-8d22-aa6dfb580b0b"

[[env.staging.r2_buckets]]
binding = "DOCUMENTS_BUCKET"
bucket_name = "freight-bill-documents-staging"

[assets]
directory = "../frontend/dist"
